### ISSUE TITLE
Analysis confusion

### ISSUE THREAD

**Issue by HarshvardhanPatel123** [HarshvardhanPatel123/Group-2-Coursework-Python#1]
I am a bit confused what they meant by 

For each of the 12 possible groups, the user should be able to carry out a simple analysis using the
current data on policyholders and claims.

Can you explain:?

**Comment by nathbuen** [comment]
I'm pretty sure the "12 possible groups" are referring to the 12 combinations you can make with the categories: age, gender and area.

**Comment by HarshvardhanPatel123** [comment]
Thanks nath!

**Comment by HarshvardhanPatel123** [comment]
Thanks

**Comment by HarshvardhanPatel123** [comment]
Understood, thanks
